# Generated by Django 5.2.7 on 2025-10-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.CharField(choices=[('haunt', 'Haunting'), ('feast', 'Feasting'), ('possess', 'Possession'), ('cult', 'Cult Activities')], default='haunt', max_length=20),
        ),
    ]
