# Generated by Django 5.2.7 on 2025-11-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='details_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='group',
            field=models.CharField(choices=[('haunt', 'Haunting'), ('possess', 'Possession'), ('rnr', 'Rest and Relaxation')], default='haunt', max_length=20),
        ),
    ]
