name: CI

on:
  push:
    branches: [main]

env:
  REGISTRY: 'registry.pds-technology.ltd'
  IMAGE_NAME: 'halloween-hackathon-2025'
  SERVICE_NAME: 'halloween-hackathon-2025'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Authenticate to Tailscale
        run: |
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=github-action-runner

      - name: Build container image
        run: docker build -t $REGISTRY/$IMAGE_NAME:latest .

      - name: Log in to Private Container Registry
        run: |
          echo ${{ secrets.REGISTRY_PASSWORD_PRODUCTION }} | docker login $REGISTRY -u ${{ secrets.REGISTRY_USER_PRODUCTION }} --password-stdin

      - name: Push image to Container Registry
        run: docker push $REGISTRY/$IMAGE_NAME:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Authenticate to Tailscale
        run: |
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=github-action-runner

      - name: Deploy to Docker Swarm via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USERNAME_PRODUCTION }}
          password: ${{ secrets.PASSWORD_PRODUCTION }}
          port: 22
          envs: IMAGE_NAME,REGISTRY,SERVICE_NAME
          script: |
            echo "Updating service..."
            echo ${{ secrets.REGISTRY_PASSWORD_PRODUCTION }} | docker login -u ${{ secrets.REGISTRY_USER_PRODUCTION }} --password-stdin $(echo $REGISTRY)
            docker service update --force --with-registry-auth --image $(echo $REGISTRY)/$(echo $IMAGE_NAME):latest $(echo $SERVICE_NAME)
